stages:
    - test
    - staging
  
test:
  image: python:3.8
  stage: test
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
    - cd backend/secfit
    - apt-get update -qy
    - pip install -r requirements.txt
    - python manage.py test

staging:
  type: deploy
  image: ruby
  stage: staging
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=sec-fit-t18 --api-key=e62dbc48-238a-4440-8547-109069068eef
  only:
    - master
