# Generated by Django 3.1 on 2021-03-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210204_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_exercise',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
