# Generated by Django 3.1 on 2021-03-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='athletes',
        ),
    ]
